# SAM deployment configuration
version = 0.1

[default.deploy.parameters]
stack_name = "pulse-engagement-tracker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l56ap6crdyy9"
s3_prefix = "pulse-engagement-tracker"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"

[prod.deploy.parameters]
stack_name = "pulse-engagement-tracker-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l56ap6crdyy9"
s3_prefix = "pulse-engagement-tracker"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
